export const MoviesData =[
    {
        id: 1,
        name:"Baby Shark",
        rate:5 ,
        date:"2020",
        duration: "1 hr 14 min",
        type:"Kids & Family , Animation ",
        url:"https://canvas-bridge.tubitv.com/OQ-7TWDJEFMwVH0GLuliAdnoI8c=/400x574/smart/img.adrise.tv/f6486342-5e78-482a-b70d-a58be8009f0a.jpg",
        description:"Let's dance to the Baby Shark song!.",
        Trailer: "https://www.youtube.com/embed/sTsu3JNqlHw" , 
        Directed: "USP Studios" , 
        descriptionsdetails: "Let's dance to the Baby Shark song!! Come join Bob the train in his preschool nursery rhymes & kids songs for babies & toddlers like balloon song, no no song, five little babies, bath song, this is the way, rain rain go away, incy wincy spider, johny johny, humpty dumpty, rig a jig jig, zoo song, wheels on the bus, pat a cake, ten in the bed, three little kittens, and more baby songs.",  
                
    },
    {
        id: 2,
        name:"Halloween",
        rate:3 ,
        date:"2019",
        duration: "1 hr 04 min",
        type:"Kids & Family , Animation",
        url:"https://canvas-bridge.tubitv.com/GlC2F-OwD8SguCeuFuUKC-wPxGg=/400x574/smart/img.adrise.tv/6258c4e4-5ad1-4ec9-aba8-640b8dcaef9f.jpg",
        description:"Celebrate Halloween with spooky songs for kids.",
        Trailer:" https://www.youtube.com/embed/anmNuKuZ0IY", 
        Directed:"USP Studios ", 
        descriptionsdetails:"Celebrate Halloween with spooky songs for kids, showcasing popular easy-to-learn nursery rhymes and educational videos for babies and toddlers. ",
    },
     {
        id: 3,
        name:"Alien Worlds",
        rate:4 ,
        date:"2020", 
        duration: "1 hr ",
        type:"Documentary",
        url:"https://canvas-bridge02.tubitv.com/2UnyQEehGJQkAZcfyPQJxaSO9yU=/0x0:900x1285/400x574/smart/img.adrise.tv/f60ddb9e-2715-4ace-812b-a0d04ac64056.jpg",
        description:"Get a look at the evidence suggesting the existence of colossal ",
        Trailer:"https://www.youtube.com/embed/CbKadIdWMow" , 
        Directed:"J. Michael LongRico Lowry ", 
        descriptionsdetails:"Get a look at the evidence suggesting the existence of colossal creatures that once towered over humans in a mysterious realm of our ancient past. ",
       
    },
    {
        id: 4,
        name:"The Underground",
        rate:2 ,
        date:"2021",
        duration: "56 min",
        type:"Documentary, Sci-Fi ",
        url:"https://canvas-bridge02.tubitv.com/4aJlOCrUKW8yb67ZdpIMokmbdc4=/400x574/smart/img.adrise.tv/f63dbf48-e6a9-4b31-8827-ffaaadd2a9ab.jpg",
        description:"Phil Schneider claims to have worked on a secret military base in Dulce, New Mexico.",
        Trailer:"https://www.youtube.com/embed/td7LNTu7cuU", 
        Directed:" Darcy Weir", 
        descriptionsdetails:"Phil Schneider claims to have worked on a secret military base in Dulce, New Mexico, where alien contact was made. This doc investigates his story. ",
        
    },

    {
        id: 5,
        name:"10/31 Part 2",
        rate:4 , 
        date:"2021",
        duration: "1 hr 45 min",
        type:"Horror ",
        url:"https://canvas-bridge02.tubitv.com/MB4J5NZfwAHYyvB2NwRO-Rog3kU=/0x0:900x1285/400x574/smart/img.adrise.tv/3305330d-a6ba-4cf0-978b-bd5dfe8593c6.jpg",
        description:"More Blood Soaked Tales of Horror and the Macabre ",
        Trailer:"https://www.youtube.com/embed/Z_G2-5obWLg", 
        Directed:"Brett DeJager, Max Groah, John Hale III, Zane Hershberger, Robert Lanphere ", 
        descriptionsdetails:"More Blood Soaked Tales of Horror and the Macabre ",
        satrring: "London Grace, Jennifer Nangle, Anastasia Elfman, David E. McMahon, R.J. Wagner "
            },
    {
        id: 6,
        name:"The Healing Garden",
        rate:3 ,
        date:"2021",
        duration: "1 hr 35 min",
        type:"Drama",
        url:"https://canvas-bridge.tubitv.com/NQ7S6RRaM3tLy5WF7Dzf1fgxUeE=/400x574/smart/img.adrise.tv/93af70b1-546a-4666-9885-c881dff28b23.jpg",
        description:"Together, an aging military chaplain and a girl from a broken home plant a miracle garden, in this faith-based drama, laced with warmth and humor.",
        Trailer:"https://www.youtube.com/embed/SdMfqRolp94", 
        Directed:"Joseph Granda", 
        descriptionsdetails:"Together, an aging military chaplain and a girl from a broken home plant a miracle garden, in this faith-based drama, laced with warmth and humor. ",
            },
   
    {
        id: 7,
        name:"Rainforest ",
        rate:4 ,
        date:"2020", 
        duration: "2 hr ",
        type:"Documentary, Lifestyle",
        url:"https://canvas-bridge02.tubitv.com/etsP-wWn4_KRBWflRxq74u6m5os=/400x574/smart/img.adrise.tv/96f8fbf4-dedb-4365-b70e-f3adfef8db3c.jpg",
        description:"Sleep peacefully and study with better focus by blocking out unwanted noise.",
        Trailer:"https://www.youtube.com/embed/UHI9LCeVNAc", 
        Directed:"Relaxing White Noise ", 
        descriptionsdetails:"Sleep peacefully and study with better focus by blocking out unwanted noise in your environment with the relaxing sounds of a tropical rainforest. ",      
    },

    {
        id: 8,
        name:"Fist of Fury",
        rate:5 ,
        date:"1972",
        duration: "1 hr 46 min",
        type:"Action, Drama ",
        url:"https://canvas-bridge.tubitv.com/n8mQKE84xGolcANTjG_97bIeNE8=/400x574/smart/img.adrise.tv/eae536d1-b19f-44c1-a7aa-67b9913fc478.jpg",
        description:"Bruce Lee stars in this iconic action film about a student who fights for the honor. ",
        Trailer:"https://www.youtube.com/embed/b8z78aQ9ogA", 
        Directed:"Wei Lo", 
        descriptionsdetails:"Bruce Lee stars in this iconic action film about a student who fights for the honor of the oppressed Chinese people and to avenge his master’s murder ",
      },

    {
        id: 9,
        name:"Payback",
        rate:4 ,
        date:"2021", 
        duration: "1 hr 31 min ",
        type:"Thriller, Crime ",
        url:"https://canvas-bridge.tubitv.com/TBOJCTPsT-n_dRrNoK_yba4lhwA=/400x574/smart/img.adrise.tv/c98b89d1-d799-42bc-84b3-a55dfe0a0ca9.jpg",
        description:"Mike Markovich, a young stockbroker at a Mob-controlled Wall Street firm. ",
        Trailer:"https://www.youtube.com/embed/PVHUOG-ofvg", 
        Directed:"Joseph Mensch ", 
        descriptionsdetails:"Mike Markovich, a young stockbroker at a Mob-controlled Wall Street firm, is betrayed and imprisoned for six years. When he is released, his deadly quest for vengeance begins.  ",
  },

    {
        id: 10,
        name:"Death Rides a Horse",
        rate:3 ,
        date:"1972",
        duration: "1 hr 54 min",
       type:"AWestern, Drama ",
        url:"https://canvas-bridge.tubitv.com/0jVnyorIPirTL0J-24GcSK1LJaQ=/38x0:1510x2100/400x574/smart/img.adrise.tv/a930107b-a975-48a2-b234-8a82095f0204.jpg",
        description:"A young man, who, as a child witnessed the slaughter of his family.",
        Trailer:"https://www.youtube.com/embed/gThuwiFSRCY" , 
        Directed:"Giulio Petroni ", 
        descriptionsdetails:"A young man, who, as a child witnessed the slaughter of his family, teams with a mysterious gunfighter to avenge their deaths. ",  
    },

    {
        id: 11,
        name:"Recon",
        rate:2 ,
        date:"2020", 
        duration: "1 hr 30 min ",
        type:"Action  ",
        url:"https://images2.vudu.com/poster2/1521410-168",
        description:"Mike Markovich, a young stockbroker at a Mob-controlled Wall Street firm.",
        Trailer:"https://www.youtube.com/embed/bUNWCpqDTOA", 
        Directed:" Recon", 
        descriptionsdetails:"Mike Markovich, a young stockbroker at a Mob-controlled Wall Street firm."
       
    },

    {
        id: 12,
        name:"The Jurassic Games",
        rate:1 ,
        date:"2018",
        duration: "1 hr 26 min",
        type:"Action, Sci-Fi ",
        url:"https://image.tmdb.org/t/p/w342/4iXYZgB0VZyPvjBfEY0f2VTMDqa.jpg",
        description:"Every year, 10 of the world's most lethal death row criminals. ",
        Trailer:"https://www.youtube.com/embed/94CozNqV0Zk", 
        Directed:" Games tv", 
        descriptionsdetails:"Every year, 10 of the world's most lethal death row criminals.In the near future, 10 death row convicts are forced to compete in a virtual reality game that pits them against dinosaurs and each other. ",
       
    },
]